<?php

namespace Restz\OpenAPI\Models;

class SecurityScheme extends AbstractModel
{
    protected static array $required_parameters = [
        'type',
        'name',
        'in',
        'scheme',
        'openIdConnectUrl',
        'flows'
    ];

    /**
     * REQUIRED. The type of the security scheme.
     * Valid values are "apiKey", "http", "oauth2", "openIdConnect".
     */
    protected string $type;
    /**
     * A short description for security scheme.
     * CommonMark syntax MAY be used for rich text representation.
     */
    protected ?string $description;
    /**
     * REQUIRED. The name of the header,
     * query or cookie parameter to be used.
     */
    protected string $name;
    /**
     * REQUIRED. The location of the API key.
     * Valid values are "query", "header" or "cookie".
     */
    protected string $in;
    /**
     * REQUIRED. The name of the HTTP Authorization scheme to be used
     * in the Authorization header as defined in RFC7235.
     * The values used SHOULD be registered in the
     * IANA Authentication Scheme registry.
     */
    protected string $scheme;
    /**
     * REQUIRED. OpenId Connect URL to discover OAuth2 configuration values.
     * This MUST be in the form of a URL.
     */
    protected string $open_id_connect_url;
    /**
     * A hint to the client to identify how the bearer token is formatted.
     * Bearer tokens are usually generated by an authorization server,
     * so this information is primarily for documentation purposes.
     */
    protected ?string $bearer_format;
    /**
     * REQUIRED. An object containing configuration
     * information for the flow types supported.
     *
     * @var OAuthFlow[]
     */
    protected array $flows;

    /**
     * SecurityScheme constructor.
     * @param  string  $type
     * @param  string|null  $description
     * @param  string  $name
     * @param  string  $in
     * @param  string  $scheme
     * @param  string  $open_id_connect_url
     * @param  string|null  $bearer_format
     * @param  OAuthFlow[]  $flows
     */
    public function __construct(
        string $type,
        ?string $description,
        string $name,
        string $in,
        string $scheme,
        string $open_id_connect_url,
        ?string $bearer_format,
        array $flows
    ) {
        $this->type = $type;
        $this->description = $description;
        $this->name = $name;
        $this->in = $in;
        $this->scheme = $scheme;
        $this->open_id_connect_url = $open_id_connect_url;
        $this->bearer_format = $bearer_format;
        $this->flows = $flows;
    }

    protected static function constructFromArray(array $data): self
    {
        $flows = $data['flows'] ?? [];

        foreach ($flows as &$oauth_flow) {
            $oauth_flow = OAuthFlow::fromArray($oauth_flow);
        }

        return new self(
            $data['type'],
            $data['description'] ?? null,
            $data['name'],
            $data['in'],
            $data['scheme'],
            $data['openIdConnectUrl'],
            $data['bearerFormat'] ?? null,
            $flows
        );
    }

    /**
     * @return string
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getIn(): string
    {
        return $this->in;
    }

    /**
     * @return string
     */
    public function getScheme(): string
    {
        return $this->scheme;
    }

    /**
     * @return string
     */
    public function getOpenIdConnectUrl(): string
    {
        return $this->open_id_connect_url;
    }

    /**
     * @return string|null
     */
    public function getBearerFormat(): ?string
    {
        return $this->bearer_format;
    }

    /**
     * @return OAuthFlow[]
     */
    public function getFlows(): array
    {
        return $this->flows;
    }
}
