<?php


namespace Restz\OpenAPI\Models;


class SecurityScheme
{
    /**
     * REQUIRED. The type of the security scheme.
     * Valid values are "apiKey", "http", "oauth2", "openIdConnect".
     */
    protected string $type;
    /**
     * A short description for security scheme.
     * CommonMark syntax MAY be used for rich text representation.
     */
    protected string $description;
    /**
     * REQUIRED. The name of the header,
     * query or cookie parameter to be used.
     */
    protected string $name;
    /**
     * REQUIRED. The location of the API key.
     * Valid values are "query", "header" or "cookie".
     */
    protected string $in;
    /**
     * REQUIRED. The name of the HTTP Authorization scheme to be used
     * in the Authorization header as defined in RFC7235.
     * The values used SHOULD be registered in the
     * IANA Authentication Scheme registry.
     */
    protected string $scheme;
    /**
     * REQUIRED. OpenId Connect URL to discover OAuth2 configuration values.
     * This MUST be in the form of a URL.
     */
    protected string $open_id_connect_url;
    /**
     * A hint to the client to identify how the bearer token is formatted.
     * Bearer tokens are usually generated by an authorization server,
     * so this information is primarily for documentation purposes.
     */
    protected string $bearer_format;
    /**
     * REQUIRED. An object containing configuration
     * information for the flow types supported.
     *
     * @var OAuthFlow[]
     */
    protected array $flows;
}
