<?php

namespace Restz\OpenAPI\Models;

class SecurityScheme implements Model
{
    /**
     * REQUIRED. The type of the security scheme.
     * Valid values are "apiKey", "http", "oauth2", "openIdConnect".
     */
    protected string $type;
    /**
     * A short description for security scheme.
     * CommonMark syntax MAY be used for rich text representation.
     */
    protected string $description;
    /**
     * REQUIRED. The name of the header,
     * query or cookie parameter to be used.
     */
    protected string $name;
    /**
     * REQUIRED. The location of the API key.
     * Valid values are "query", "header" or "cookie".
     */
    protected string $in;
    /**
     * REQUIRED. The name of the HTTP Authorization scheme to be used
     * in the Authorization header as defined in RFC7235.
     * The values used SHOULD be registered in the
     * IANA Authentication Scheme registry.
     */
    protected string $scheme;
    /**
     * REQUIRED. OpenId Connect URL to discover OAuth2 configuration values.
     * This MUST be in the form of a URL.
     */
    protected string $open_id_connect_url;
    /**
     * A hint to the client to identify how the bearer token is formatted.
     * Bearer tokens are usually generated by an authorization server,
     * so this information is primarily for documentation purposes.
     */
    protected string $bearer_format;
    /**
     * REQUIRED. An object containing configuration
     * information for the flow types supported.
     *
     * @var OAuthFlow[]
     */
    protected array $flows;

    /**
     * SecurityScheme constructor.
     * @param  string  $type
     * @param  string  $description
     * @param  string  $name
     * @param  string  $in
     * @param  string  $scheme
     * @param  string  $open_id_connect_url
     * @param  string  $bearer_format
     * @param  OAuthFlow[]  $flows
     */
    public function __construct(
        string $type,
        string $description,
        string $name,
        string $in,
        string $scheme,
        string $open_id_connect_url,
        string $bearer_format,
        array $flows
    ) {
        $this->type = $type;
        $this->description = $description;
        $this->name = $name;
        $this->in = $in;
        $this->scheme = $scheme;
        $this->open_id_connect_url = $open_id_connect_url;
        $this->bearer_format = $bearer_format;
        $this->flows = $flows;
    }

    public static function fromArray(array $data): Model
    {
        // TODO: Implement fromArray() method.
    }
}
